In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/Veremi_final_dataset.csv")

df.head()

,Unnamed: 0,type,rcvTime,pos_0,pos_1,pos_noise_0,pos_noise_1,spd_0,spd_1,spd_noise_0,...,acl_0,acl_1,acl_noise_0,acl_noise_1,hed_0,hed_1,hed_noise_0,hed_noise_1,attack,attack_type
0,0,3,27371.216284,981.098535,908.497891,3.826423,3.964059,-17.723786,-2.154895,-0.024182,...,-0.248402,-0.177659,0.000784,1.114785e-03,-0.971331,-0.237732,44.022409,33.840519,0,RandomSpeedOffset
1,1,3,52060.561117,1213.025174,984.277524,4.477449,4.459375,14.504808,2.605276,-0.008523,...,-0.653850,-0.117125,0.000001,1.847528e-07,0.992578,0.121610,2.560114,8.414909,0,DataReplay
2,2,3,28156.319142,140.514133,944.338854,2.965184,3.066191,-0.346027,4.671520,-0.000469,...,0.333247,-4.486889,0.000448,6.050771e-03,0.256103,0.966649,15.915074,9.636057,1,DoSDisruptive
3,3,3,28671.375689,558.005547,327.316562,4.934159,5.037039,11.792797,4.028876,0.022346,...,-0.030639,-0.010265,0.000066,2.237617e-05,0.954113,0.299446,2.854203,6.203941,1,RandomSpeedOffset
4,4,2,53612.000000,689.179631,547.143780,3.327547,3.374621,3.887137,-8.732709,0.000090,...,-1.829939,4.111129,0.000028,6.361425e-05,0.360402,-0.932797,5.648109,19.951521,0,DoS

In [3]:
df.shape

(22165610, 21)

In [4]:
df.info

<bound method DataFrame.info of           Unnamed: 0  type       rcvTime        pos_0       pos_1  \
0                  0     3  27371.216284   981.098535  908.497891
1                  1     3  52060.561117  1213.025174  984.277524
2                  2     3  28156.319142   140.514133  944.338854
3                  3     3  28671.375689   558.005547  327.316562
4                  4     2  53612.000000   689.179631  547.143780
...              ...   ...           ...          ...         ...
22165605    22165605     3  26625.228276   269.115394  221.485812
22165606    22165606     3  27500.186511   224.666440  859.740381
22165607    22165607     3  50555.773355   809.926551  758.261899
22165608    22165608     3  53185.074189   647.564971  700.928206
22165609    22165609     3  26880.811175   129.360138  885.843582

          pos_noise_0  pos_noise_1      spd_0      spd_1  spd_noise_0  ...  \
0            3.826423     3.964059 -17.723786  -2.154895    -0.024182  ...
1            4.477449     4.459375  14.504808   2.605276    -0.008523  ...
2            2.965184     3.066191  -0.346027   4.671520    -0.000469  ...
3            4.934159     5.037039  11.792797   4.028876     0.022346  ...
4            3.327547     3.374621   3.887137  -8.732709     0.000090  ...
...               ...          ...        ...        ...          ...  ...
22165605     3.639919     3.386238  -8.300488  -1.330502     0.016346  ...
22165606     3.223376     3.139665  -2.230908  14.447055     0.003544  ...
22165607     3.845163     3.521880  -7.527460   3.662441     0.009083  ...
22165608     4.226780     4.343972  -0.119584  -0.053815    -0.000026  ...
22165609     4.084995     4.020910 -12.996989   5.603057     0.012725  ...

             acl_0     acl_1  acl_noise_0   acl_noise_1     hed_0     hed_1  \
0        -0.248402 -0.177659     0.000784  1.114785e-03 -0.971331 -0.237732
1        -0.653850 -0.117125     0.000001  1.847528e-07  0.992578  0.121610
2         0.333247 -4.486889     0.000448  6.050771e-03  0.256103  0.966649
3        -0.030639 -0.010265     0.000066  2.237617e-05  0.954113  0.299446
4        -1.829939  4.111129     0.000028  6.361425e-05  0.360402 -0.932797
...            ...       ...          ...           ...       ...       ...
22165605  4.446163  0.716958     0.007319  4.833149e-03 -0.998507  0.054632
22165606 -0.023170  0.156311     0.000065  1.722914e-05  0.158782  0.987314
22165607 -1.612424  0.784034     0.001494  2.158883e-03 -0.781532  0.623865
22165608  0.094900  0.042773     0.000033  1.484357e-05 -0.993449 -0.114277
22165609  2.138142  0.129366     0.005911  1.008848e-03 -0.990889  0.134683

          hed_noise_0  hed_noise_1  attack         attack_type
0           44.022409    33.840519       0   RandomSpeedOffset
1            2.560114     8.414909       0          DataReplay
2           15.915074     9.636057       1       DoSDisruptive
3            2.854203     6.203941       1   RandomSpeedOffset
4            5.648109    19.951521       0                 DoS
...               ...          ...     ...                 ...
22165605    17.373540     8.653378       0            ConstPos
22165606    15.243281     2.875833       1          DataReplay
22165607    30.244891     9.878268       0  DoSDisruptiveSybil
22165608    14.846941    14.749614       0   RandomSpeedOffset
22165609    26.350811    14.969964       1   RandomSpeedOffset

[22165610 rows x 21 columns]>

In [5]:
df.columns

Index(['Unnamed: 0', 'type', 'rcvTime', 'pos_0', 'pos_1', 'pos_noise_0',
       'pos_noise_1', 'spd_0', 'spd_1', 'spd_noise_0', 'spd_noise_1', 'acl_0',
       'acl_1', 'acl_noise_0', 'acl_noise_1', 'hed_0', 'hed_1', 'hed_noise_0',
       'hed_noise_1', 'attack', 'attack_type'],
      dtype='object')

In [12]:
df.describe()

,Unnamed: 0,type,rcvTime,pos_0,pos_1,pos_noise_0,pos_noise_1,spd_0,spd_1,spd_noise_0,spd_noise_1,acl_0,acl_1,acl_noise_0,acl_noise_1,hed_0,hed_1,hed_noise_0,hed_noise_1,attack
count,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07,2.216561e+07
mean,1.108280e+07,2.862252e+00,3.854859e+04,5.329721e+02,6.603367e+02,4.046188e+00,4.046512e+00,1.208355e+00,1.840707e+00,3.907324e-05,-4.067774e-05,4.326139e-02,3.133031e-02,8.046429e-04,9.885709e-04,-6.650189e-02,3.548430e-02,1.353572e+01,1.331680e+01,4.526968e-01
std,6.398661e+06,3.446356e-01,1.242552e+04,4.116284e+02,3.172246e+02,1.560484e+01,1.560468e+01,9.359781e+00,9.750929e+00,1.159198e-02,1.270705e-02,9.413520e-01,1.195764e+00,2.508699e-03,2.569196e-03,6.412466e-01,7.481906e-01,2.075428e+01,2.115640e+01,4.977574e-01
min,0.000000e+00,2.000000e+00,2.520200e+04,-3.302072e+03,-1.772355e+03,0.000000e+00,0.000000e+00,-2.898100e+01,-2.711331e+01,-9.632719e-02,-9.251237e-02,-4.499949e+00,-4.499996e+00,0.000000e+00,0.000000e+00,-1.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,5.541402e+06,3.000000e+00,2.715477e+04,1.953475e+02,3.876745e+02,3.490113e+00,3.491588e+00,-2.367673e+00,-3.906020e+00,-2.354647e-03,-4.018850e-03,-1.646441e-01,-2.050368e-01,4.597348e-06,5.411226e-06,-6.560285e-01,-7.727252e-01,3.921042e+00,3.525630e+00,0.000000e+00
50%,1.108280e+07,3.000000e+00,2.859619e+04,2.746182e+02,7.189812e+02,3.990211e+00,3.989890e+00,7.293842e-05,3.737540e-04,-0.000000e+00,0.000000e+00,7.356967e-05,1.023528e-04,6.490463e-05,6.664388e-05,-2.467192e-02,5.588878e-02,9.340904e+00,8.197616e+00,0.000000e+00
75%,1.662421e+07,3.000000e+00,5.193184e+04,9.018468e+02,9.048708e+02,4.491021e+00,4.491310e+00,4.527563e+00,7.824899e+00,2.454594e-03,3.942456e-03,2.137943e-01,3.048999e-01,4.541221e-04,7.559112e-04,2.153790e-01,8.479934e-01,1.735634e+01,1.711693e+01,1.000000e+00
max,2.216561e+07,3.000000e+00,5.419800e+04,3.052571e+03,3.153994e+03,1.395861e+04,1.395862e+04,3.999999e+01,3.999999e+01,8.860860e-02,9.533098e-02,4.506160e+00,4.505410e+00,1.276282e-01,1.248708e-01,1.000000e+00,1.000000e+00,6.339722e+03,6.304234e+03,1.000000e+00

## Description du dataset VeReMi

Le dataset contient environ 22 millions d'observations et plusieurs variables décrivant les données du véhicule lui-même (type=2) et les messages reçus d’ autres véhicules (type=3)

Les variables incluent :
- la position des véhicules
- la vitesse
- l'accélération
- la direction
- les valeurs de bruit 

Le dataset contient également deux variables liées aux attaques :

- `attack` : indique si le message correspond à un comportement normal ou malveillant
- `attack_type` : indique le type d'attaque spécifique

In [8]:
df["attack_type"].value_counts()

attack_type
GridSybil             1246576
DoS                   1228655
DoSDisruptive         1224482
DoSRandom             1223169
DoSDisruptiveSybil    1185897
DoSRandomSybil        1185897
DataReplaySybil       1143918
DelayedMessages       1143918
ConstSpeedOffset      1143918
DataReplay            1143918
RandomSpeed           1143918
RandomPosOffset       1143918
RandomPos             1143918
Disruptive            1143918
EventualStop          1143918
ConstPos              1143918
ConstSpeed            1143918
ConstPosOffset        1143918
RandomSpeedOffset     1143918
Name: count, dtype: int64

In [9]:
df["attack"].value_counts()

attack
0    12131310
1    10034300
Name: count, dtype: int64

In [15]:
df["type"].value_counts()

type
3    19112335
2     3053275
Name: count, dtype: int64

In [10]:
df.isnull().sum()

Unnamed: 0     0
type           0
rcvTime        0
pos_0          0
pos_1          0
pos_noise_0    0
pos_noise_1    0
spd_0          0
spd_1          0
spd_noise_0    0
spd_noise_1    0
acl_0          0
acl_1          0
acl_noise_0    0
acl_noise_1    0
hed_0          0
hed_1          0
hed_noise_0    0
hed_noise_1    0
attack         0
attack_type    0
dtype: int64

In [11]:
df.duplicated().sum()

0

## Analyse des attaques dans le dataset

L'analyse des variables liées aux attaques montre que le dataset est relativement équilibré. 
La variable `attack` indique si une observation correspond à un comportement normal ou à une attaque. 
On observe environ 12 millions d'observations normales contre environ 10 millions correspondant à des attaques.

La variable `attack_type` permet d'identifier le type précis de l'attaque. Le dataset contient 19 types d'attaques différents. Le nombre d'observations est assez proche pour chaque type d'attaque.

L'analyse du dataset montre qu'il n'y a pas de valeurs manquantes ni de doublons dans les données

In [13]:
df = df.drop(columns=["Unnamed: 0"])

In [14]:
df.columns

Index(['type', 'rcvTime', 'pos_0', 'pos_1', 'pos_noise_0', 'pos_noise_1',
       'spd_0', 'spd_1', 'spd_noise_0', 'spd_noise_1', 'acl_0', 'acl_1',
       'acl_noise_0', 'acl_noise_1', 'hed_0', 'hed_1', 'hed_noise_0',
       'hed_noise_1', 'attack', 'attack_type'],
      dtype='object')